/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TournamentsRouteImport } from './routes/tournaments'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as NotesRouteImport } from './routes/notes'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as ExamsRouteImport } from './routes/exams'
import { Route as DonateRouteImport } from './routes/donate'
import { Route as CoursesRouteImport } from './routes/courses'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as UUsernameRouteImport } from './routes/u.$username'
import { Route as TournamentsIdRouteImport } from './routes/tournaments.$id'
import { Route as TakeExamIdRouteImport } from './routes/take.$examId'
import { Route as PracticeCourseIdRouteImport } from './routes/practice.$courseId'
import { Route as GuestExamCourseIdRouteImport } from './routes/guest-exam.$courseId'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedProfileRouteImport } from './routes/_authenticated/profile'
import { Route as AuthenticatedOnboardingRouteImport } from './routes/_authenticated/onboarding'
import { Route as AuthenticatedLeaderboardRouteImport } from './routes/_authenticated/leaderboard'
import { Route as AuthenticatedFriendsRouteImport } from './routes/_authenticated/friends'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedChatRouteImport } from './routes/_authenticated/chat'
import { Route as AuthenticatedChallengesRouteImport } from './routes/_authenticated/challenges'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin.index'
import { Route as AuthenticatedTournamentAttemptIdRouteImport } from './routes/_authenticated/tournament.$attemptId'
import { Route as AuthenticatedResultsAttemptIdRouteImport } from './routes/_authenticated/results.$attemptId'
import { Route as AuthenticatedExamAttemptIdRouteImport } from './routes/_authenticated/exam.$attemptId'
import { Route as AuthenticatedCoursesCodeRouteImport } from './routes/_authenticated/courses.$code'
import { Route as AuthenticatedChallengeChallengeIdRouteImport } from './routes/_authenticated/challenge.$challengeId'
import { Route as AuthenticatedAdminCourseCourseIdRouteImport } from './routes/_authenticated/admin.course.$courseId'

const TournamentsRoute = TournamentsRouteImport.update({
  id: '/tournaments',
  path: '/tournaments',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const NotesRoute = NotesRouteImport.update({
  id: '/notes',
  path: '/notes',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ExamsRoute = ExamsRouteImport.update({
  id: '/exams',
  path: '/exams',
  getParentRoute: () => rootRouteImport,
} as any)
const DonateRoute = DonateRouteImport.update({
  id: '/donate',
  path: '/donate',
  getParentRoute: () => rootRouteImport,
} as any)
const CoursesRoute = CoursesRouteImport.update({
  id: '/courses',
  path: '/courses',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const UUsernameRoute = UUsernameRouteImport.update({
  id: '/u/$username',
  path: '/u/$username',
  getParentRoute: () => rootRouteImport,
} as any)
const TournamentsIdRoute = TournamentsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => TournamentsRoute,
} as any)
const TakeExamIdRoute = TakeExamIdRouteImport.update({
  id: '/take/$examId',
  path: '/take/$examId',
  getParentRoute: () => rootRouteImport,
} as any)
const PracticeCourseIdRoute = PracticeCourseIdRouteImport.update({
  id: '/practice/$courseId',
  path: '/practice/$courseId',
  getParentRoute: () => rootRouteImport,
} as any)
const GuestExamCourseIdRoute = GuestExamCourseIdRouteImport.update({
  id: '/guest-exam/$courseId',
  path: '/guest-exam/$courseId',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedProfileRoute = AuthenticatedProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedOnboardingRoute = AuthenticatedOnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedLeaderboardRoute =
  AuthenticatedLeaderboardRouteImport.update({
    id: '/leaderboard',
    path: '/leaderboard',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedFriendsRoute = AuthenticatedFriendsRouteImport.update({
  id: '/friends',
  path: '/friends',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedChatRoute = AuthenticatedChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedChallengesRoute = AuthenticatedChallengesRouteImport.update({
  id: '/challenges',
  path: '/challenges',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedTournamentAttemptIdRoute =
  AuthenticatedTournamentAttemptIdRouteImport.update({
    id: '/tournament/$attemptId',
    path: '/tournament/$attemptId',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedResultsAttemptIdRoute =
  AuthenticatedResultsAttemptIdRouteImport.update({
    id: '/results/$attemptId',
    path: '/results/$attemptId',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedExamAttemptIdRoute =
  AuthenticatedExamAttemptIdRouteImport.update({
    id: '/exam/$attemptId',
    path: '/exam/$attemptId',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedCoursesCodeRoute =
  AuthenticatedCoursesCodeRouteImport.update({
    id: '/courses/$code',
    path: '/courses/$code',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedChallengeChallengeIdRoute =
  AuthenticatedChallengeChallengeIdRouteImport.update({
    id: '/challenge/$challengeId',
    path: '/challenge/$challengeId',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminCourseCourseIdRoute =
  AuthenticatedAdminCourseCourseIdRouteImport.update({
    id: '/admin/course/$courseId',
    path: '/admin/course/$courseId',
    getParentRoute: () => AuthenticatedRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/courses': typeof CoursesRoute
  '/donate': typeof DonateRoute
  '/exams': typeof ExamsRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/notes': typeof NotesRoute
  '/reset-password': typeof ResetPasswordRoute
  '/tournaments': typeof TournamentsRouteWithChildren
  '/challenges': typeof AuthenticatedChallengesRoute
  '/chat': typeof AuthenticatedChatRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/friends': typeof AuthenticatedFriendsRoute
  '/leaderboard': typeof AuthenticatedLeaderboardRoute
  '/onboarding': typeof AuthenticatedOnboardingRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/guest-exam/$courseId': typeof GuestExamCourseIdRoute
  '/practice/$courseId': typeof PracticeCourseIdRoute
  '/take/$examId': typeof TakeExamIdRoute
  '/tournaments/$id': typeof TournamentsIdRoute
  '/u/$username': typeof UUsernameRoute
  '/challenge/$challengeId': typeof AuthenticatedChallengeChallengeIdRoute
  '/courses/$code': typeof AuthenticatedCoursesCodeRoute
  '/exam/$attemptId': typeof AuthenticatedExamAttemptIdRoute
  '/results/$attemptId': typeof AuthenticatedResultsAttemptIdRoute
  '/tournament/$attemptId': typeof AuthenticatedTournamentAttemptIdRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
  '/admin/course/$courseId': typeof AuthenticatedAdminCourseCourseIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/courses': typeof CoursesRoute
  '/donate': typeof DonateRoute
  '/exams': typeof ExamsRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/notes': typeof NotesRoute
  '/reset-password': typeof ResetPasswordRoute
  '/tournaments': typeof TournamentsRouteWithChildren
  '/challenges': typeof AuthenticatedChallengesRoute
  '/chat': typeof AuthenticatedChatRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/friends': typeof AuthenticatedFriendsRoute
  '/leaderboard': typeof AuthenticatedLeaderboardRoute
  '/onboarding': typeof AuthenticatedOnboardingRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/guest-exam/$courseId': typeof GuestExamCourseIdRoute
  '/practice/$courseId': typeof PracticeCourseIdRoute
  '/take/$examId': typeof TakeExamIdRoute
  '/tournaments/$id': typeof TournamentsIdRoute
  '/u/$username': typeof UUsernameRoute
  '/challenge/$challengeId': typeof AuthenticatedChallengeChallengeIdRoute
  '/courses/$code': typeof AuthenticatedCoursesCodeRoute
  '/exam/$attemptId': typeof AuthenticatedExamAttemptIdRoute
  '/results/$attemptId': typeof AuthenticatedResultsAttemptIdRoute
  '/tournament/$attemptId': typeof AuthenticatedTournamentAttemptIdRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
  '/admin/course/$courseId': typeof AuthenticatedAdminCourseCourseIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/auth': typeof AuthRoute
  '/courses': typeof CoursesRoute
  '/donate': typeof DonateRoute
  '/exams': typeof ExamsRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/notes': typeof NotesRoute
  '/reset-password': typeof ResetPasswordRoute
  '/tournaments': typeof TournamentsRouteWithChildren
  '/_authenticated/challenges': typeof AuthenticatedChallengesRoute
  '/_authenticated/chat': typeof AuthenticatedChatRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/friends': typeof AuthenticatedFriendsRoute
  '/_authenticated/leaderboard': typeof AuthenticatedLeaderboardRoute
  '/_authenticated/onboarding': typeof AuthenticatedOnboardingRoute
  '/_authenticated/profile': typeof AuthenticatedProfileRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/guest-exam/$courseId': typeof GuestExamCourseIdRoute
  '/practice/$courseId': typeof PracticeCourseIdRoute
  '/take/$examId': typeof TakeExamIdRoute
  '/tournaments/$id': typeof TournamentsIdRoute
  '/u/$username': typeof UUsernameRoute
  '/_authenticated/challenge/$challengeId': typeof AuthenticatedChallengeChallengeIdRoute
  '/_authenticated/courses/$code': typeof AuthenticatedCoursesCodeRoute
  '/_authenticated/exam/$attemptId': typeof AuthenticatedExamAttemptIdRoute
  '/_authenticated/results/$attemptId': typeof AuthenticatedResultsAttemptIdRoute
  '/_authenticated/tournament/$attemptId': typeof AuthenticatedTournamentAttemptIdRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
  '/_authenticated/admin/course/$courseId': typeof AuthenticatedAdminCourseCourseIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/courses'
    | '/donate'
    | '/exams'
    | '/forgot-password'
    | '/notes'
    | '/reset-password'
    | '/tournaments'
    | '/challenges'
    | '/chat'
    | '/dashboard'
    | '/friends'
    | '/leaderboard'
    | '/onboarding'
    | '/profile'
    | '/settings'
    | '/guest-exam/$courseId'
    | '/practice/$courseId'
    | '/take/$examId'
    | '/tournaments/$id'
    | '/u/$username'
    | '/challenge/$challengeId'
    | '/courses/$code'
    | '/exam/$attemptId'
    | '/results/$attemptId'
    | '/tournament/$attemptId'
    | '/admin/'
    | '/admin/course/$courseId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/courses'
    | '/donate'
    | '/exams'
    | '/forgot-password'
    | '/notes'
    | '/reset-password'
    | '/tournaments'
    | '/challenges'
    | '/chat'
    | '/dashboard'
    | '/friends'
    | '/leaderboard'
    | '/onboarding'
    | '/profile'
    | '/settings'
    | '/guest-exam/$courseId'
    | '/practice/$courseId'
    | '/take/$examId'
    | '/tournaments/$id'
    | '/u/$username'
    | '/challenge/$challengeId'
    | '/courses/$code'
    | '/exam/$attemptId'
    | '/results/$attemptId'
    | '/tournament/$attemptId'
    | '/admin'
    | '/admin/course/$courseId'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/courses'
    | '/donate'
    | '/exams'
    | '/forgot-password'
    | '/notes'
    | '/reset-password'
    | '/tournaments'
    | '/_authenticated/challenges'
    | '/_authenticated/chat'
    | '/_authenticated/dashboard'
    | '/_authenticated/friends'
    | '/_authenticated/leaderboard'
    | '/_authenticated/onboarding'
    | '/_authenticated/profile'
    | '/_authenticated/settings'
    | '/guest-exam/$courseId'
    | '/practice/$courseId'
    | '/take/$examId'
    | '/tournaments/$id'
    | '/u/$username'
    | '/_authenticated/challenge/$challengeId'
    | '/_authenticated/courses/$code'
    | '/_authenticated/exam/$attemptId'
    | '/_authenticated/results/$attemptId'
    | '/_authenticated/tournament/$attemptId'
    | '/_authenticated/admin/'
    | '/_authenticated/admin/course/$courseId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  AuthRoute: typeof AuthRoute
  CoursesRoute: typeof CoursesRoute
  DonateRoute: typeof DonateRoute
  ExamsRoute: typeof ExamsRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  NotesRoute: typeof NotesRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  TournamentsRoute: typeof TournamentsRouteWithChildren
  GuestExamCourseIdRoute: typeof GuestExamCourseIdRoute
  PracticeCourseIdRoute: typeof PracticeCourseIdRoute
  TakeExamIdRoute: typeof TakeExamIdRoute
  UUsernameRoute: typeof UUsernameRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/tournaments': {
      id: '/tournaments'
      path: '/tournaments'
      fullPath: '/tournaments'
      preLoaderRoute: typeof TournamentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notes': {
      id: '/notes'
      path: '/notes'
      fullPath: '/notes'
      preLoaderRoute: typeof NotesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/exams': {
      id: '/exams'
      path: '/exams'
      fullPath: '/exams'
      preLoaderRoute: typeof ExamsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/donate': {
      id: '/donate'
      path: '/donate'
      fullPath: '/donate'
      preLoaderRoute: typeof DonateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/courses': {
      id: '/courses'
      path: '/courses'
      fullPath: '/courses'
      preLoaderRoute: typeof CoursesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/u/$username': {
      id: '/u/$username'
      path: '/u/$username'
      fullPath: '/u/$username'
      preLoaderRoute: typeof UUsernameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tournaments/$id': {
      id: '/tournaments/$id'
      path: '/$id'
      fullPath: '/tournaments/$id'
      preLoaderRoute: typeof TournamentsIdRouteImport
      parentRoute: typeof TournamentsRoute
    }
    '/take/$examId': {
      id: '/take/$examId'
      path: '/take/$examId'
      fullPath: '/take/$examId'
      preLoaderRoute: typeof TakeExamIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/practice/$courseId': {
      id: '/practice/$courseId'
      path: '/practice/$courseId'
      fullPath: '/practice/$courseId'
      preLoaderRoute: typeof PracticeCourseIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guest-exam/$courseId': {
      id: '/guest-exam/$courseId'
      path: '/guest-exam/$courseId'
      fullPath: '/guest-exam/$courseId'
      preLoaderRoute: typeof GuestExamCourseIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/profile': {
      id: '/_authenticated/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthenticatedProfileRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/onboarding': {
      id: '/_authenticated/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof AuthenticatedOnboardingRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/leaderboard': {
      id: '/_authenticated/leaderboard'
      path: '/leaderboard'
      fullPath: '/leaderboard'
      preLoaderRoute: typeof AuthenticatedLeaderboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/friends': {
      id: '/_authenticated/friends'
      path: '/friends'
      fullPath: '/friends'
      preLoaderRoute: typeof AuthenticatedFriendsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/chat': {
      id: '/_authenticated/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof AuthenticatedChatRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/challenges': {
      id: '/_authenticated/challenges'
      path: '/challenges'
      fullPath: '/challenges'
      preLoaderRoute: typeof AuthenticatedChallengesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/tournament/$attemptId': {
      id: '/_authenticated/tournament/$attemptId'
      path: '/tournament/$attemptId'
      fullPath: '/tournament/$attemptId'
      preLoaderRoute: typeof AuthenticatedTournamentAttemptIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/results/$attemptId': {
      id: '/_authenticated/results/$attemptId'
      path: '/results/$attemptId'
      fullPath: '/results/$attemptId'
      preLoaderRoute: typeof AuthenticatedResultsAttemptIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/exam/$attemptId': {
      id: '/_authenticated/exam/$attemptId'
      path: '/exam/$attemptId'
      fullPath: '/exam/$attemptId'
      preLoaderRoute: typeof AuthenticatedExamAttemptIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/courses/$code': {
      id: '/_authenticated/courses/$code'
      path: '/courses/$code'
      fullPath: '/courses/$code'
      preLoaderRoute: typeof AuthenticatedCoursesCodeRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/challenge/$challengeId': {
      id: '/_authenticated/challenge/$challengeId'
      path: '/challenge/$challengeId'
      fullPath: '/challenge/$challengeId'
      preLoaderRoute: typeof AuthenticatedChallengeChallengeIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/course/$courseId': {
      id: '/_authenticated/admin/course/$courseId'
      path: '/admin/course/$courseId'
      fullPath: '/admin/course/$courseId'
      preLoaderRoute: typeof AuthenticatedAdminCourseCourseIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedChallengesRoute: typeof AuthenticatedChallengesRoute
  AuthenticatedChatRoute: typeof AuthenticatedChatRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedFriendsRoute: typeof AuthenticatedFriendsRoute
  AuthenticatedLeaderboardRoute: typeof AuthenticatedLeaderboardRoute
  AuthenticatedOnboardingRoute: typeof AuthenticatedOnboardingRoute
  AuthenticatedProfileRoute: typeof AuthenticatedProfileRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedChallengeChallengeIdRoute: typeof AuthenticatedChallengeChallengeIdRoute
  AuthenticatedCoursesCodeRoute: typeof AuthenticatedCoursesCodeRoute
  AuthenticatedExamAttemptIdRoute: typeof AuthenticatedExamAttemptIdRoute
  AuthenticatedResultsAttemptIdRoute: typeof AuthenticatedResultsAttemptIdRoute
  AuthenticatedTournamentAttemptIdRoute: typeof AuthenticatedTournamentAttemptIdRoute
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
  AuthenticatedAdminCourseCourseIdRoute: typeof AuthenticatedAdminCourseCourseIdRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedChallengesRoute: AuthenticatedChallengesRoute,
  AuthenticatedChatRoute: AuthenticatedChatRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedFriendsRoute: AuthenticatedFriendsRoute,
  AuthenticatedLeaderboardRoute: AuthenticatedLeaderboardRoute,
  AuthenticatedOnboardingRoute: AuthenticatedOnboardingRoute,
  AuthenticatedProfileRoute: AuthenticatedProfileRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedChallengeChallengeIdRoute:
    AuthenticatedChallengeChallengeIdRoute,
  AuthenticatedCoursesCodeRoute: AuthenticatedCoursesCodeRoute,
  AuthenticatedExamAttemptIdRoute: AuthenticatedExamAttemptIdRoute,
  AuthenticatedResultsAttemptIdRoute: AuthenticatedResultsAttemptIdRoute,
  AuthenticatedTournamentAttemptIdRoute: AuthenticatedTournamentAttemptIdRoute,
  AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
  AuthenticatedAdminCourseCourseIdRoute: AuthenticatedAdminCourseCourseIdRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

interface TournamentsRouteChildren {
  TournamentsIdRoute: typeof TournamentsIdRoute
}

const TournamentsRouteChildren: TournamentsRouteChildren = {
  TournamentsIdRoute: TournamentsIdRoute,
}

const TournamentsRouteWithChildren = TournamentsRoute._addFileChildren(
  TournamentsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  AuthRoute: AuthRoute,
  CoursesRoute: CoursesRoute,
  DonateRoute: DonateRoute,
  ExamsRoute: ExamsRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  NotesRoute: NotesRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  TournamentsRoute: TournamentsRouteWithChildren,
  GuestExamCourseIdRoute: GuestExamCourseIdRoute,
  PracticeCourseIdRoute: PracticeCourseIdRoute,
  TakeExamIdRoute: TakeExamIdRoute,
  UUsernameRoute: UUsernameRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
